#!/bin/bash
set -e
# If the script was invoked with sh, re-exec under bash so bash-specific
# features like PIPESTATUS work correctly.
if [ -z "${BASH_VERSION:-}" ]; then
    if command -v bash >/dev/null 2>&1; then
        exec bash "$0" "$@"
    else
        echo "[-] 错误：此脚本需要 bash，请使用 bash 运行：sudo bash $0 <interface>" >&2
        exit 1
    fi
fi
# Base directory of the script (absolute) to reliably locate .env when
# the script is executed via sudo or different working directories.
BASE_DIR=$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd)

########################################
# 依赖检查（全新机器必需）
########################################
check_dependency() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "[-] 错误：缺少依赖 '$1'，请先安装：apt install -y $2"
        exit 1
    fi
}

check_dependency docker "docker.io docker-compose-plugin"
check_dependency curl "curl"
check_dependency jq "jq"
check_dependency unzip "unzip"
check_dependency openssl "openssl"

# 检查 docker compose 子命令（v2 插件）
if ! docker compose version >/dev/null 2>&1; then
    echo "[-] 错误：需要 Docker Compose V2（docker compose 子命令），请安装 docker-compose-plugin"
    exit 1
fi

echo "[+] 依赖检查通过"

usage() {
    cat <<EOF
Usage: $0 <interface>

You must specify the network interface to use with Suricata and Zeek.
Example: sudo sh ./deploy.sh ens192
EOF
}

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    usage
    exit 0
fi

if [ -z "$1" ]; then
    echo "[-] 错误：必须指定网卡接口。"
    usage
    exit 1
fi

INTERFACE=$1
export INTERFACE

if command -v ip >/dev/null 2>&1; then
    if ! ip link show "$INTERFACE" >/dev/null 2>&1; then
        echo "[-] 错误：网卡接口 '$INTERFACE' 不存在。"
        exit 1
    fi
    echo "[*] 0. 配置网络接口 $INTERFACE：开启混杂模式并禁用 offload"
    ip link set "$INTERFACE" promisc on
fi

if command -v ethtool >/dev/null 2>&1; then
    ethtool -K "$INTERFACE" gro off || true
    ethtool -K "$INTERFACE" lro off || true
    ethtool -K "$INTERFACE" tso off || true
    ethtool -K "$INTERFACE" gso off || true
    # 禁用 RX/TX checksum offload，避免网卡硬件计算 checksum 导致
    # Zeek/Suricata 在混杂模式下捕获到错误 checksum（如 tcp checksum incorrect），
    # 进而影响 payload 解析和 http_request_body 提取
    ethtool -K "$INTERFACE" rx off || true
    ethtool -K "$INTERFACE" tx off || true
fi

# 持久化网卡配置：创建 systemd 服务，重启后自动恢复混杂模式和 offload 禁用
NET_SERVICE="/etc/systemd/system/sensemind-network.service"
cat > "$NET_SERVICE" << EOF
[Unit]
Description=SenseMind network interface configuration
After=network.target network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/bash -c 'ip link set $INTERFACE promisc on; ethtool -K $INTERFACE gro off lro off tso off gso off rx off tx off 2>/dev/null || true'

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable sensemind-network.service 2>/dev/null
echo "[+] 网卡配置已持久化（sensemind-network.service，开机自动执行）"

export PUID=$(id -u)
export PGID=$(id -g)

echo "[*] 构建/拉取 Docker 镜像..."

# 证书生成依赖 elasticsearch 镜像（certutil），需提前拉取
ES_IMAGE="docker.elastic.co/elasticsearch/elasticsearch:8.19.16"
if ! docker image inspect "$ES_IMAGE" >/dev/null 2>&1; then
    echo "[*] 拉取 Elasticsearch 镜像（证书生成依赖）..."
    docker pull "$ES_IMAGE" || {
        echo "[-] 拉取 Elasticsearch 镜像失败，请检查网络/代理。"
        exit 1
    }
fi

########################################
# 0.1 预生成 Elasticsearch SSL 证书
#     在启动任何容器之前生成，打破"先有ES还是先有证书"的循环依赖
########################################
CERTS_DIR="$BASE_DIR/certs"
if [ ! -f "$CERTS_DIR/elastic-certificates.p12" ] || [ ! -f "$CERTS_DIR/ca.crt" ]; then
    echo "[*] 生成 Elasticsearch SSL 证书（首次部署，有效期 10 年）..."
    mkdir -p "$CERTS_DIR"
    # ES 容器内 certutil 以 uid 1000(elasticsearch) 运行，而本目录由 sudo(root)
    # 创建且默认 755，uid 1000 无法写入会抛 AccessDeniedException。临时放开写权限。
    chmod 777 "$CERTS_DIR"

    # 1. 生成 CA（PEM 格式，便于 Logstash 使用）
    #    -s/--silent 抑制 certutil 默认输出的大段帮助说明
    #    --dn 自定义 CA 公用名（默认为 Elastic Certificate Tool Autogenerated CA）
    docker run --rm \
        -v "$CERTS_DIR:/certs" \
        --entrypoint /usr/share/elasticsearch/bin/elasticsearch-certutil \
        docker.elastic.co/elasticsearch/elasticsearch:8.19.16 \
        ca --pem --out /certs/ca.zip --days 3650 -s \
        --ca-dn "CN=SenseMind CA,O=SenseMind"

    # 2. 解压 CA → certs/ca/ca.crt, certs/ca/ca.key
    if ! command -v unzip >/dev/null 2>&1; then
        echo "[-] 错误：需要 unzip 工具来解压证书，请先安装：apt install -y unzip"
        exit 1
    fi
    (cd "$CERTS_DIR" && unzip -oq ca.zip)

    # 3. 生成节点证书（PKCS12，用于 ES transport + HTTP SSL）
    docker run --rm \
        -v "$CERTS_DIR:/certs" \
        --entrypoint /usr/share/elasticsearch/bin/elasticsearch-certutil \
        docker.elastic.co/elasticsearch/elasticsearch:8.19.16 \
        cert --out /certs/elastic-certificates.p12 --pass "" \
        --ca-cert /certs/ca/ca.crt --ca-key /certs/ca/ca.key \
        --dns elasticsearch,localhost --ip 127.0.0.1 --days 3650 -s

    # 4. 将 ca.crt 复制到 certs 根目录，方便挂载
    cp "$CERTS_DIR/ca/ca.crt" "$CERTS_DIR/ca.crt"

    # 5. 清理临时文件
    rm -f "$CERTS_DIR/ca.zip"

    # 6. 设置权限
    chmod 644 "$CERTS_DIR/ca.crt" "$CERTS_DIR/elastic-certificates.p12"

    echo "[+] SSL 证书已生成: $CERTS_DIR/"
    echo "    - ca.crt                    (CA 证书，Logstash 用)"
    echo "    - elastic-certificates.p12   (节点证书，ES 用)"
else
    echo "[+] SSL 证书已存在，跳过生成"
fi

########################################
# 0.1.1 为 web 前端签发 HTTPS 证书
#       复用 ES 的 CA（ca.crt + ca.key），SAN 包含本机 IP，供 nginx 使用
########################################
if [ ! -f "$CERTS_DIR/web.crt" ] || [ ! -f "$CERTS_DIR/web.key" ]; then
    echo "[*] 为 web 前端签发 HTTPS 证书（复用 ES CA）..."
    # 收集本机非 loopback IPv4 地址，加入 SAN（浏览器用 IP 访问时需匹配）
    WEB_SAN="DNS:localhost,IP:127.0.0.1"
    for ip in $(hostname -I 2>/dev/null | tr ' ' '\n' | grep -E '^[0-9]+\.' | grep -v '^127\.' | sort -u); do
        WEB_SAN="${WEB_SAN},IP:${ip}"
    done
    # 生成私钥
    openssl genrsa -out "$CERTS_DIR/web.key" 2048 2>/dev/null
    # 生成 CSR
    openssl req -new -key "$CERTS_DIR/web.key" -out "$CERTS_DIR/web.csr" \
        -subj "/CN=sensemind-web" 2>/dev/null
    # SAN 扩展配置
    printf "subjectAltName=%s\nextendedKeyUsage=serverAuth\n" "$WEB_SAN" > "$CERTS_DIR/web.ext"
    # 用 ES 的 CA 签发（有效期 10 年）
    openssl x509 -req -in "$CERTS_DIR/web.csr" \
        -CA "$CERTS_DIR/ca/ca.crt" -CAkey "$CERTS_DIR/ca/ca.key" \
        -CAcreateserial -out "$CERTS_DIR/web.crt" -days 3650 -sha256 \
        -extfile "$CERTS_DIR/web.ext" 2>/dev/null
    # 清理临时文件（-CAcreateserial 在 CA 同目录生成 ca.srl）
    rm -f "$CERTS_DIR/web.csr" "$CERTS_DIR/web.ext" "$CERTS_DIR/ca/ca.srl"
    chmod 644 "$CERTS_DIR/web.crt"
    chmod 600 "$CERTS_DIR/web.key"
    echo "[+] web HTTPS 证书已签发: web.crt / web.key"
    echo "    SAN: $WEB_SAN"
    echo "    注意：自签 CA，浏览器首次访问会提示不安全，导入 certs/ca.crt 到系统/浏览器信任库即可消除"
else
    echo "[+] web HTTPS 证书已存在，跳过签发"
fi

########################################
# 0.2 清理残留容器
#     - 非全新部署时，上次失败可能残留容器，按服务名强制移除避免重名冲突
########################################
echo "[*] 清理可能残留的旧容器..."
docker compose down --remove-orphans 2>/dev/null >/dev/null || true
docker compose config --services 2>/dev/null | xargs -r docker rm -f >/dev/null 2>&1 || true

echo "[*] =============================================="

echo "[*] 1. 初始化环境变量文件..."
ENV_FILE="$BASE_DIR/.env"
if [ -f "$ENV_FILE" ]; then
    cp -f "$ENV_FILE" "${ENV_FILE}.bak" >/dev/null 2>&1 || true
fi
touch "$ENV_FILE"
chmod 600 "$ENV_FILE"
echo "[+] 环境变量文件已就绪: $ENV_FILE（权限 600）"

# Ensure LOGSTASH_API_KEY exists to avoid docker-compose warnings when referenced
grep -q '^LOGSTASH_API_KEY=' "$ENV_FILE" 2>/dev/null || echo 'LOGSTASH_API_KEY=' >> "$ENV_FILE"

# 持久化监听网卡到 .env，避免后续 docker compose 重启（如 reboot、手动 up）
# 回退到默认 ens192 导致 Suricata/Zeek 因网卡不存在而崩溃
grep -q '^INTERFACE=' "$ENV_FILE" 2>/dev/null && \
  sed -i "s/^INTERFACE=.*/INTERFACE=$INTERFACE/" "$ENV_FILE" || \
  echo "INTERFACE=$INTERFACE" >> "$ENV_FILE"

# 确保 filebeat.yml 的权限和所有者符合 Filebeat 要求
if [ -f "$BASE_DIR/filebeat/filebeat.yml" ]; then
    echo "[*] 修改 filebeat/filebeat.yml 权限，确保容器内 filebeat 可读取"
    chown root:root "$BASE_DIR/filebeat/filebeat.yml"
    chmod 600 "$BASE_DIR/filebeat/filebeat.yml"
fi

# 预创建宿主机 Suricata/Zeek 目录，以便日志、配置和规则持久化
mkdir -p /data/suricata/logs /data/suricata/lib /data/suricata/lib/rules /data/suricata/etc /data/zeek/logs
chmod 755 /data /data/suricata /data/zeek /data/suricata/logs /data/suricata/lib /data/suricata/lib/rules /data/suricata/etc /data/zeek/logs

# 创建 Zeek 日志过滤脚本（仅保留 conn 做全流量记录，dns/http/ssl 不再输出）。
# 注意：必须创建为"文件"，docker 才会把宿主机路径作为文件挂载到 /opt/zeek-log-filter.zeek；
# 若此处漏建，docker 会自动用同名"空目录"挂载，导致 zeek 把目录当包加载而崩溃循环。
if [ ! -f /data/zeek/zeek-log-filter.zeek ]; then
    cat > /data/zeek/zeek-log-filter.zeek <<'ZEEK_FILTER_EOF'
# SenseMind Zeek 日志过滤脚本
# 保留 conn + http 日志；dns / ssl / packet_filter 不再输出。
# 本脚本随 zeek 启动命令加载（未经过 site/local.zeek）。
#
# 实现：
#   1. 运行时遍历 Log::active_streams 反向保留（priority=-10），禁用基础协议流
#   2. PacketFilter::LOG 在 zeek_init &priority=5 创建（晚于 -10），且第一条记录在
#      zeek_init 期间就写入，disable_stream 来不及。改用 hook PacketFilter::log_policy
#      直接 break 否决所有写入，从根本上阻止 packet_filter.log 产生。
#   注：zeek priority 数值越小越先执行。

# Zeek 日志轮转统一由 logrotate 管理（create 模式 + postrotate docker restart zeek）。
redef LogAscii::enable_leftover_log_rotation = T;

module SenseMindFilter;

# 保留的日志流：conn（全流量记录）+ http（联合查询语义分析）
const keep_streams: set[Log::ID] = {
    Conn::LOG,
    HTTP::LOG,
};

# 禁用基础协议流（在默认 priority 的 zeek_init 之后执行）
event zeek_init() &priority=-10
    {
    # 先收集待禁用的流，再统一禁用；避免在遍历 active_streams 的同时
    # disable_stream 修改该表引发迭代器失效（iterator invalidation）。
    local to_disable: set[Log::ID] = set();
    for ( sid in Log::active_streams )
        {
        if ( sid !in keep_streams )
            add to_disable[sid];
        }
    for ( sid in to_disable )
        Log::disable_stream(sid);
    }

# PacketFilter::LOG 在 zeek_init &priority=5 创建，第一条记录在 install() 里立即写入，
# disable_stream（即使 priority=10）来不及拦截。直接 hook 其 log_policy 用 break 否决。
hook PacketFilter::log_policy(rec: PacketFilter::Info, id: Log::ID, filter: Log::Filter)
    {
    break;
    }

# 减少 conn.log 体积：写盘前剔除与 SOC 分析冗余或纯噪音的连接。
const conn_noise_ports: set[port] = {
    53/udp, 53/tcp,
    5355/udp, 5353/udp, 1900/udp,
    137/udp, 138/udp, 139/tcp,
    123/udp, 67/udp, 68/udp,
};

# Zeek 8.2 移除 filter$invalidate 字段，改用 break 否决该记录写入。
hook Conn::log_policy(rec: Conn::Info, id: Log::ID, filter: Log::Filter)
    {
    if ( ! rec?$id ) return;
    if ( rec$id$resp_p in conn_noise_ports )
        break;
    if ( rec$id$resp_h in 224.0.0.0/4 )
        break;
    }

ZEEK_FILTER_EOF
    chmod 644 /data/zeek/zeek-log-filter.zeek
fi

chown -R "$PUID:$PGID" /data/suricata/logs /data/suricata/lib /data/suricata/lib/rules /data/suricata/etc

echo "[*] 2. 准备 elastic 密码并启动 Elasticsearch..."
# ES 8.x 首次启动（安全索引不存在）时，若设置了 ELASTIC_PASSWORD 环境变量，
# 会以此引导 elastic 用户密码；后续启动忽略该变量。
# 这避免了在 SSL 启用后 elasticsearch-reset-password CLI（需信任自签 CA）的麻烦。
EXISTING_PWD=$(grep '^ELASTIC_PASSWORD=' "$ENV_FILE" 2>/dev/null | cut -d= -f2-)
if [ -n "$EXISTING_PWD" ]; then
    ELASTIC_PASSWORD="$EXISTING_PWD"
    echo "[+] 使用已有 elastic 密码"
else
    ELASTIC_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)
    grep -v '^ELASTIC_PASSWORD=' "$ENV_FILE" 2>/dev/null > "${ENV_FILE}.tmp" || true
    echo "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}" >> "${ENV_FILE}.tmp"
    mv "${ENV_FILE}.tmp" "$ENV_FILE"
    chmod 600 "$ENV_FILE"
    echo "[+] elastic 密码已生成并写入 .env（ES 首次启动将以引导）"
fi
export ELASTIC_PASSWORD

docker compose up -d elasticsearch

echo "[*] 3. 等待 Elasticsearch 完全就绪..."
while true; do
    # 获取容器当前运行状态和健康状态
    STATUS=$(docker inspect --format='{{.State.Status}}' elasticsearch 2>/dev/null || echo "not_found")
    HEALTH=$(docker inspect --format='{{.State.Health.Status}}' elasticsearch 2>/dev/null || echo "none")

    if [ "$HEALTH" = "healthy" ]; then
        printf "\n[+] Elasticsearch 已进入 Healthy 状态!\n"
        break
    fi

    if [ "$STATUS" != "running" ]; then
        printf "\n[-] 错误：Elasticsearch 容器未能成功运行，当前状态：%s\n" "$STATUS"
        exit 1
    fi

    printf "."
    sleep 2
done

echo "[*] 3.1 验证 elastic 密码..."
# 密码已在启动 ES 前写入 .env，ES 首次启动时以 ELASTIC_PASSWORD 引导。
# 此处仅验证密码是否生效（curl -sk 跳过证书校验，从宿主机经端口映射访问）。
PWD_OK=false
for i in $(seq 1 20); do
    PWD_CHECK=$(curl -sk -o /dev/null -w "%{http_code}" --max-time 5 \
        -u "elastic:${ELASTIC_PASSWORD}" "https://localhost:9200/" 2>/dev/null) || true
    if [ "$PWD_CHECK" = "200" ]; then
        PWD_OK=true
        echo "[+] elastic 密码验证通过 (尝试 $i/20)"
        break
    fi
    printf "."
    sleep 3
done

if [ "$PWD_OK" != "true" ]; then
    printf "\n[-] 错误：elastic 密码验证失败（最后 HTTP 状态码: %s）\n" "${PWD_CHECK:-000}"
    echo "[-] 若复用旧数据卷(esdata)，ES 会忽略 ELASTIC_PASSWORD 而沿用旧密码。"
    echo "[-] 请清理后重试：sudo bash remove.sh && sudo bash deploy.sh $INTERFACE"
    exit 1
fi

echo "[*] 3.2 正在等待 Elasticsearch 安全模块完全就绪..."

# 使用脚本开头定义的 BASE_DIR 绝对路径加载环境变量
if [ ! -f "$BASE_DIR/.env" ]; then
    echo "[-] 致命错误：找不到 $BASE_DIR/.env"
    exit 1
fi
. "$BASE_DIR/.env"

# 显式检查密码变量
if [ -z "${ELASTIC_PASSWORD}" ]; then
    echo "[-] 致命错误：ELASTIC_PASSWORD 为空！.env 内容如下："
    grep "PASSWORD\|TOKEN\|KEY" "$BASE_DIR/.env" || true
    exit 1
fi

AUTH_READY=false
for i in $(seq 1 20); do
    # 分离 curl 执行与状态码提取，避免管道或子shell导致的 set -e 陷阱
    CURL_OUTPUT=$(curl -sk -o /dev/null -w "%{http_code}" --max-time 5 \
        -u "elastic:${ELASTIC_PASSWORD}" \
        "https://localhost:9200/_security/_authenticate" 2>/dev/null) || true
    
    AUTH_CODE="${CURL_OUTPUT:-000}"
    
    if [ "$AUTH_CODE" = "200" ]; then
        AUTH_READY=true
        echo "[+] Elasticsearch 安全模块已就绪 (尝试 $i/20)"
        break
    fi
    
    printf "."
    sleep 3
done

if [ "$AUTH_READY" != "true" ]; then
    echo ""
    echo "[-] 错误：Elasticsearch 安全模块在 60 秒内未就绪"
    echo "[-] 最后认证响应码: ${AUTH_CODE}"
    docker logs elasticsearch --tail 50 2>&1 | grep -iE "security|exception|error|authentication" || true
    exit 1
fi

echo "[*] 3.4 正在生成 logstash API Key..."

# 确保从 .env 读取到最新的密码
. "$ENV_FILE"

if [ -z "$ELASTIC_PASSWORD" ]; then
    echo "[-] 错误：.env 中未找到 ELASTIC_PASSWORD"
    exit 1
fi

# 增加重试机制，等待安全索引同步完成
MAX_RETRIES=10
RETRY_COUNT=0
LOGSTASH_API_KEY=""

while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
    RESPONSE=$(curl -sk -u "elastic:${ELASTIC_PASSWORD}" \
        -X POST "https://localhost:9200/_security/api_key" \
        -H "Content-Type: application/json" \
        -d '{
          "name": "logstash-soc",
          "role_descriptors": {
            "logstash_writer": {
              "cluster": ["monitor", "read_ilm", "manage_index_templates", "manage_ingest_pipelines"],
              "index": [
                {
                  "names": ["*"],
                  "privileges": ["write", "create", "create_index", "auto_configure", "view_index_metadata"]
                }
              ]
            }
          }
        }')

    # 尝试解析 API Key
    LOGSTASH_API_KEY=$(echo "$RESPONSE" | jq -r 'if .id and .api_key then (.id + ":" + .api_key) else empty end' 2>/dev/null)

    if [ -n "$LOGSTASH_API_KEY" ] && [ "$LOGSTASH_API_KEY" != "null:null" ]; then
        break
    fi

    RETRY_COUNT=$((RETRY_COUNT + 1))
    echo "[!] API Key 生成失败 (尝试 $RETRY_COUNT/$MAX_RETRIES)，ES 响应: $RESPONSE"
    echo "[*] 等待 3 秒后重试..."
    sleep 3
done

if [ -z "$LOGSTASH_API_KEY" ] || [ "$LOGSTASH_API_KEY" = "null:null" ]; then
    echo "[-] 错误：API Key 生成失败，已达最大重试次数"
    echo "[-] 最后一次 ES 响应: $RESPONSE"
    exit 1
fi

echo "[+] logstash API Key 已生成并验证通过"

export LOGSTASH_API_KEY

# 写入 .env（追加）
grep -v '^LOGSTASH_API_KEY=' "$ENV_FILE" 2>/dev/null > "${ENV_FILE}.tmp" || true
echo "LOGSTASH_API_KEY=${LOGSTASH_API_KEY}" >> "${ENV_FILE}.tmp"
mv "${ENV_FILE}.tmp" "$ENV_FILE"
chmod 600 "$ENV_FILE"

echo "[+] logstash API Key 已生成并写入 .env"

echo "[*] 3.5 正在生成 ES Reader API Key (sensemind-reader)..."

# 先清理可能存在的同名旧 API Key，避免累积（幂等）
OLD_ES_READER_IDS=$(curl -sk -u "elastic:${ELASTIC_PASSWORD}" \
    "https://localhost:9200/_security/api_key?name=sensemind-reader" 2>/dev/null \
    | jq -r '.api_keys[]? | select(.invalidated==false) | .id' 2>/dev/null) || true
for kid in $OLD_ES_READER_IDS; do
    curl -sk -u "elastic:${ELASTIC_PASSWORD}" -X DELETE \
        "https://localhost:9200/_security/api_key" \
        -H "Content-Type: application/json" \
        -d "{\"ids\":[\"$kid\"]}" >/dev/null 2>&1 || true
done

# 创建专用只读 API Key：仅授予 soc-*/soc-ai-* 索引读权限
# ai-analyzer 使用此 Key 替代 elastic 密码访问 ES（最小权限原则）
ES_READER_RESP=$(curl -sk -u "elastic:${ELASTIC_PASSWORD}" \
    -X POST "https://localhost:9200/_security/api_key" \
    -H "Content-Type: application/json" \
    -d '{
      "name": "sensemind-reader",
      "role_descriptors": {
        "sensemind_reader": {
          "cluster": ["monitor"],
          "index": [
            {
              "names": ["soc-*", "soc-ai-*"],
              "privileges": ["read", "view_index_metadata"]
            }
          ]
        }
      }
    }')

# 取 encoded 字段（已为 id:api_key 的 Base64 编码，可直接用于 Authorization: ApiKey 头）
ES_READER_API_KEY=$(echo "$ES_READER_RESP" | jq -r '.encoded // empty' 2>/dev/null)

if [ -z "$ES_READER_API_KEY" ]; then
    echo "[-] 错误：sensemind-reader API Key 生成失败！ES 响应: $ES_READER_RESP"
    exit 1
fi

echo "[+] ES Reader API Key 已生成"
export ES_READER_API_KEY

# 写入 .env（更新或追加）
grep -v '^ES_READER_API_KEY=' "$ENV_FILE" 2>/dev/null > "${ENV_FILE}.tmp" || true
echo "ES_READER_API_KEY=${ES_READER_API_KEY}" >> "${ENV_FILE}.tmp"
mv "${ENV_FILE}.tmp" "$ENV_FILE"
chmod 600 "$ENV_FILE"

echo "[+] ES Reader API Key 已写入 .env"

# 3.5.5 初始化 ES 索引模板（索引优化：白名单字段建索引 + best_compression）
# soc-* 模板（原始日志）：仅对搜索/过滤/排序字段建索引，其余 250+ 字段仅存储不索引
# soc-ai-* 模板（AI 研判）：仅对搜索/聚合字段建索引
# 模板永久注册在 ES 中，新索引自动套用，旧索引不受影响
echo "[*] 3.5.5 正在初始化 ES 索引模板与索引优化..."
ES_TMPL_DIR="$BASE_DIR/ai-analyzer/scripts"
# 注意：curl 不带 -f 时 HTTP 4xx/5xx 仍返回退出码 0，必须用 -w 提取状态码判断注册是否成功
TMPL_CODE=$(curl -sk -o /dev/null -w "%{http_code}" --max-time 10 \
    -u "elastic:${ELASTIC_PASSWORD}" \
    -X PUT "https://localhost:9200/_index_template/soc-template" \
    -H "Content-Type: application/json" \
    -d @"$ES_TMPL_DIR/es_template_soc.json") || true
if [ "$TMPL_CODE" != "200" ]; then
    echo "[-] soc-template 注册失败 (HTTP ${TMPL_CODE:-000})，请检查 es_template_soc.json"
    exit 1
fi
echo "[+] soc-template 已注册"

TMPL_CODE=$(curl -sk -o /dev/null -w "%{http_code}" --max-time 10 \
    -u "elastic:${ELASTIC_PASSWORD}" \
    -X PUT "https://localhost:9200/_index_template/soc-ai-template" \
    -H "Content-Type: application/json" \
    -d @"$ES_TMPL_DIR/es_template_soc_ai.json") || true
if [ "$TMPL_CODE" != "200" ]; then
    echo "[-] soc-ai-template 注册失败 (HTTP ${TMPL_CODE:-000})，请检查 es_template_soc_ai.json"
    exit 1
fi
echo "[+] soc-ai-template 已注册"

# 修正现有索引 replicas → 0（单节点无需副本），不影响新索引（模板已设 0）
# 使用通配符幂等操作，多次执行无副作用
curl -sk -u "elastic:${ELASTIC_PASSWORD}" \
    -X PUT "https://localhost:9200/soc-*/_settings" \
    -H "Content-Type: application/json" \
    -d '{"index":{"number_of_replicas":0}}' >/dev/null 2>&1 || true
curl -sk -u "elastic:${ELASTIC_PASSWORD}" \
    -X PUT "https://localhost:9200/soc-ai-*/_settings" \
    -H "Content-Type: application/json" \
    -d '{"index":{"number_of_replicas":0}}' >/dev/null 2>&1 || true
echo "[+] 索引 replicas 已设为 0（含已有索引）"

# 3.5.5b 验证新索引可写入
# PUT 模板成功（HTTP 200）≠ mapping 有效。若动态模板有误（如 match_mapping_type:"*" 误匹配
# object 类型应用 doc_values:false），写入会整条 400 被拒，Logstash 直接 drop 导致 soc-* 静默丢数据。
# 此处向临时索引（自动套用刚注册的模板）写入一条含嵌套对象的最小文档，验证通过后删除。
verify_index_write() {
    local prefix="$1"
    local idx="${prefix}-verify-$(date +%s)"
    local code
    code=$(curl -sk -o /dev/null -w "%{http_code}" --max-time 10 \
        -u "elastic:${ELASTIC_PASSWORD}" \
        -X POST "https://localhost:9200/${idx}/_doc" \
        -H "Content-Type: application/json" \
        -d '{
          "@timestamp": "2026-08-14T00:00:00.000Z",
          "event": {"dataset": "verify", "kind": "event"},
          "network": {"community_id": "verify-test"},
          "source": {"ip": "10.0.0.1", "port": 12345},
          "some_nested_object": {"sub": "value"},
          "some_long_field": 42
        }') || true
    curl -sk -u "elastic:${ELASTIC_PASSWORD}" \
        -X DELETE "https://localhost:9200/${idx}" >/dev/null 2>&1 || true
    if [ "$code" = "201" ] || [ "$code" = "200" ]; then
        echo "[+] ${prefix}-template 写入验证通过 (HTTP $code)"
        return 0
    fi
    echo "[-] ${prefix}-template 写入验证失败 (HTTP ${code:-000})"
    echo "[-] 请检查 ai-analyzer/scripts/es_template_soc*.json 的动态模板配置"
    return 1
}

echo "[*] 3.5.5b 验证新索引可写入..."
verify_index_write "soc" || exit 1
verify_index_write "soc-ai" || exit 1

echo "[*] 3.5 正在生成 JWT 与加密密钥..."
# SECRET_KEY: JWT 签名密钥（32 字节 hex），用于认证 token 签发与校验
# ENCRYPT_KEY: TOTP secret 加密密钥，用于 Fernet/PBKDF2 派生
# 仅首次生成，后续部署复用 .env 中已有值（密钥不可变更，否则已有 JWT 失效、TOTP 无法解密）
EXISTING_SECRET_KEY=$(grep '^SECRET_KEY=' "$ENV_FILE" 2>/dev/null | cut -d= -f2-)
EXISTING_ENCRYPT_KEY=$(grep '^ENCRYPT_KEY=' "$ENV_FILE" 2>/dev/null | cut -d= -f2-)

if [ -z "$EXISTING_SECRET_KEY" ]; then
    SECRET_KEY=$(openssl rand -hex 32)
    echo "SECRET_KEY=${SECRET_KEY}" >> "$ENV_FILE"
    echo "[+] SECRET_KEY 已生成并写入 .env"
else
    echo "[+] 使用已有 SECRET_KEY"
fi

if [ -z "$EXISTING_ENCRYPT_KEY" ]; then
    # core/security.py 用 PBKDF2 从 ENCRYPT_KEY 派生 Fernet 密钥，对格式不敏感，任意字符串即可
    ENCRYPT_KEY=$(openssl rand -base64 32)
    echo "ENCRYPT_KEY=${ENCRYPT_KEY}" >> "$ENV_FILE"
    echo "[+] ENCRYPT_KEY 已生成并写入 .env"
else
    echo "[+] 使用已有 ENCRYPT_KEY"
fi
chmod 600 "$ENV_FILE"

# 4. 一键拉起整套 SOC 堆栈（Suricata, Zeek）
#    先构建本地镜像（web、ai-analyzer），避免 up 时尝试从远程拉取本地镜像
echo "[*] 4. 正在拉起探针与展示层..."

# 预拉取构建基础镜像（BuildKit 不走 Docker daemon 代理，需先 docker pull 缓存到本地）
BASE_IMAGES="python:3.12-slim node:20-alpine nginx:1.27-alpine"
for IMG in $BASE_IMAGES; do
    if ! docker image inspect "$IMG" >/dev/null 2>&1; then
        echo "[+] 拉取基础镜像 $IMG ..."
        docker pull "$IMG" || echo "[!] 拉取 $IMG 失败，若已有缓存可继续。"
    fi
done

docker compose build
docker compose up -d

echo "[*] 4.1 强制重启 logstash 以加载最新 API Key..."
docker compose up -d --force-recreate logstash

echo "[*] 4.2 强制重启 ai-analyzer 以加载 ES Reader API Key..."
docker compose up -d --force-recreate ai-analyzer

# 修改 Suricata 配置：community-id、payload、http-body-inline、local.rules
# jasonish/suricata 容器启动时会自动复制默认配置到挂载目录
SURICATA_YAML="/data/suricata/etc/suricata.yaml"
if [ -f "$SURICATA_YAML" ]; then
    # 初始化两个规则文件（规则目录与 suricata.yaml 的 default-rule-path 一致: /var/lib/suricata/rules）
    # - local.rules：只存放系统(AI)自动生成的规则，初始化时创建空文件
    # - combined.rules：初始规则 + 外部规则集，初始化时创建空文件（内容在第 5 步填充）
    LOCAL_RULES="/data/suricata/lib/rules/local.rules"
    COMBINED_RULES="/data/suricata/lib/rules/combined.rules"
    : > "$LOCAL_RULES"   # 清空/创建 local.rules
    : > "$COMBINED_RULES"  # 清空/创建 combined.rules
    chmod 644 "$LOCAL_RULES" "$COMBINED_RULES"
    echo "[+] 已初始化空 local.rules（仅供 AI 自动生成规则写入）与 combined.rules"

    # 开启 alert 事件的 HTTP body 记录，供 AI 判断攻击是否成功
    # http-body: Base64 编码的完整响应体（保留中文），由 ai-analyzer 解码
    # http-body-printable: 可打印格式（中文被替换为.），作为回退
    # 两者都是 - alert: 部分的选项，需要 metadata 启用才会生效
    # 同时清理 - http: 部分下旧版误加的非注释 http-body-printable 行
    sed -i -E \
      -e 's/community-id: false/community-id: true/' \
      -e '/- alert:/,/- frame:/ { s/# *(payload-buffer-size:)/\1/; s/# *(payload-printable:)/\1/; s/# *(http-body-printable:)/\1/; s/# *(http-body: yes)/\1/ }' \
      -e '/^[[:space:]]*- http:/,/^[[:space:]]*- [a-z]/ { /^[[:space:]]*http-body-printable:/d }' \
      -e 's/http-body-inline: auto/http-body-inline: yes/' \
      "$SURICATA_YAML"

    # 保留 local.rules 仅用于 AI 自动生成规则
    # suricata 8.x unix-command 默认 enabled: auto，无需额外配置
    if grep -q 'suricata\.rules' "$SURICATA_YAML"; then
        sed -i 's/- suricata\.rules/- combined.rules/' "$SURICATA_YAML"
    fi
    grep -q 'combined.rules' "$SURICATA_YAML" || \
        sed -i '/^rule-files:/a\  - combined.rules' "$SURICATA_YAML"
    if ! grep -q 'local.rules' "$SURICATA_YAML"; then
        sed -i '/- combined\.rules/a\  - local.rules' "$SURICATA_YAML"
    fi

    # 源头禁用 eve-log 的 stats/flow/mdns/files/snmp/dcerpc（SOC 不入库，纯协议元数据噪音）
    sed -i -E \
      -e '/^[[:space:]]{8}- stats:/,/^[[:space:]]*# bi-directional flows/ s/^/# /' \
      -e 's/^([[:space:]]{8})- flow$/# \1- flow/' \
      -e 's/^([[:space:]]{8})- mdns:$/# \1- mdns:/' \
      -e 's/^([[:space:]]{8})- files:$/# \1- files:/' \
      -e 's/^([[:space:]]{12})force-magic: no.*$/# \1force-magic: no/' \
      -e 's/^([[:space:]]{8})- snmp$/# \1- snmp/' \
      -e 's/^([[:space:]]{8})- dcerpc$/# \1- dcerpc/' \
      "$SURICATA_YAML"

    # af-packet 抓包优化：命令行 -i ${INTERFACE} 会绕过 af-packet 块默认参数，
    # 默认 ring-size 过小在高流量镜像口下内核丢包严重（实测 12.5%），攻击流量被随机丢弃。
    # 修复：interface 用 default 通配符（实际接口仍由 -i 传入，兼容不同设备网卡名），
    # threads/ring-size 显式优化；cluster-type 保持 Suricata 默认 cluster_flow（
    # 实测 cluster_flow + ring-size 65536 既不打散流（pkt_on_wrong_thread=0）也不丢包，
    # 优于 cluster_cpu——cluster_cpu 会把同一 TCP 流打散到多线程导致流重组失败、漏检攻击）。
    # 注意：sed 地址范围 /^af-packet:/,/^[a-z][a-z-]*:/ 限定只在 af-packet 块内替换，
    # 避免误伤 pcap/netmap/ebpf 等其它模块的 interface/threads 配置。
    sed -i -E \
      '/^af-packet:/,/^[a-z][a-z-]*:/ { s/^([[:space:]]*)- interface: .*$/\1- interface: default/; s/^([[:space:]]*)#?threads: .*$/\1threads: 16/; s/^([[:space:]]*)#?ring-size: .*$/\1ring-size: 65536/; }' \
      "$SURICATA_YAML"

    echo "[+] Suricata 配置已更新（规则文件将随后加载）"
else
    echo "[-] 警告：Suricata 配置文件 $SURICATA_YAML 未找到，跳过配置修改。"
fi

echo "[*] 4.3 关闭所有 suricata-update 规则源并清空 legacy 规则..."
# 先更新源列表，再全部禁用（抛弃 suricata-update 体系，改用自定义规则集）
docker exec --user suricata suricata suricata-update update-sources 2>/dev/null || true
docker exec suricata sh -c "suricata-update list-sources 2>/dev/null | sed -E 's/\x1b\[[0-9;]*m//g' | tr -d '\r' | awk '/^Name:/{print \$2}' | while read src; do suricata-update disable-source \"\$src\" 2>/dev/null || true; done"
# 清空 suricata-update 生成的旧规则文件（combined.rules 将取而代之）
sudo bash -c 'echo "" > /data/suricata/lib/rules/suricata.rules' 2>/dev/null || true
echo "[+] 所有 suricata-update 源已关闭，旧规则已清空"

echo "[*] 5. 下载三个外部规则集并合并到 combined.rules..."
# 兜底：SURICATA_YAML 不存在时上面 if 块未定义此变量，这里重新声明；同时清空重置（重复运行时避免重复追加）
COMBINED_RULES="/data/suricata/lib/rules/combined.rules"
: > "$COMBINED_RULES"  # 清空 combined.rules，准备重新合并

# 先写入项目内的初始规则（combined.rules，sid 已偏移到 90001 起，避开 AI 自动生成的 9000001 起区间）
# 手写规则在前，外部三集追加在后
if [ -f "$BASE_DIR/suricata/combined.rules" ]; then
    cat "$BASE_DIR/suricata/combined.rules" >> "$COMBINED_RULES"
    echo "[+] 初始规则已写入 combined.rules 头部"
else
    echo "[!] 警告：$BASE_DIR/suricata/combined.rules 不存在，跳过初始规则"
fi

TMP_RULES=$(mktemp -d)
# 确保退出时清理临时目录
cleanup_tmp() { rm -rf "$TMP_RULES"; }
trap cleanup_tmp EXIT

# 1. PT Rules (Positive Technologies) — 需要 User-Agent 否则 403
echo "[*] 5.1 下载 PT Rules (Positive Technologies)..."
PT_OK=false
if wget -q --timeout=180 --tries=3 --user-agent="Mozilla/5.0" \
    -O "$TMP_RULES/ptopen-all.rules.tar.gz" \
    "https://rules.ptsecurity.com/files/ptopen-all.rules.tar.gz"; then
    if [ -f "$TMP_RULES/ptopen-all.rules.tar.gz" ] && [ -s "$TMP_RULES/ptopen-all.rules.tar.gz" ]; then
        mkdir -p "$TMP_RULES/ptrules"
        tar -xzf "$TMP_RULES/ptopen-all.rules.tar.gz" -C "$TMP_RULES/ptrules" 2>/dev/null || true
        PT_COUNT=$(find "$TMP_RULES/ptrules" -name "*.rules" -type f -exec grep -ch '^alert\|^drop\|^reject' {} + 2>/dev/null | awk '{s+=$1}END{print s+0}')
        find "$TMP_RULES/ptrules" -name "*.rules" -type f -exec cat {} + >> "$COMBINED_RULES"
        PT_OK=true
        echo "  PT Rules: 已提取 ${PT_COUNT} 条规则"
    fi
fi
if [ "$PT_OK" != "true" ]; then
    echo "  [!] PT Rules 下载失败或为空，跳过"
fi

# 2. Stamus Lateral Movement Ruleset
echo "[*] 5.2 下载 Stamus Lateral Movement Ruleset..."
STAMUS_OK=false
if wget -q --timeout=180 --tries=3 --user-agent="Mozilla/5.0" \
    -O "$TMP_RULES/stamus-lateral-rules.tar.gz" \
    "https://ti.stamus-networks.io/open/stamus-lateral-rules.tar.gz"; then
    if [ -f "$TMP_RULES/stamus-lateral-rules.tar.gz" ] && [ -s "$TMP_RULES/stamus-lateral-rules.tar.gz" ]; then
        mkdir -p "$TMP_RULES/stamus"
        tar -xzf "$TMP_RULES/stamus-lateral-rules.tar.gz" -C "$TMP_RULES/stamus" 2>/dev/null || true
        STAMUS_COUNT=$(find "$TMP_RULES/stamus" -name "*.rules" -type f -exec grep -ch '^alert\|^drop\|^reject' {} + 2>/dev/null | awk '{s+=$1}END{print s+0}')
        find "$TMP_RULES/stamus" -name "*.rules" -type f -exec cat {} + >> "$COMBINED_RULES"
        STAMUS_OK=true
        echo "  Stamus Lateral: 已提取 ${STAMUS_COUNT} 条规则"
    fi
fi
if [ "$STAMUS_OK" != "true" ]; then
    echo "  [!] Stamus Lateral Movement 下载失败或为空，跳过"
fi

# 3. Snort Community Rules
echo "[*] 5.3 下载 Snort Community Rules..."
SNORT_OK=false
if wget -q --timeout=180 --tries=3 --user-agent="Mozilla/5.0" \
    -O "$TMP_RULES/community-rules.tar.gz" \
    "https://www.snort.org/downloads/community/community-rules.tar.gz"; then
    if [ -f "$TMP_RULES/community-rules.tar.gz" ] && [ -s "$TMP_RULES/community-rules.tar.gz" ]; then
        mkdir -p "$TMP_RULES/snort"
        tar -xzf "$TMP_RULES/community-rules.tar.gz" -C "$TMP_RULES/snort" 2>/dev/null || true
        SNORT_COUNT=$(find "$TMP_RULES/snort" -name "*.rules" -type f -exec grep -ch '^alert\|^drop\|^reject' {} + 2>/dev/null | awk '{s+=$1}END{print s+0}')
        find "$TMP_RULES/snort" -name "*.rules" -type f -exec cat {} + >> "$COMBINED_RULES"
        SNORT_OK=true
        echo "  Snort Community: 已提取 ${SNORT_COUNT} 条规则"
    fi
fi
if [ "$SNORT_OK" != "true" ]; then
    echo "  [!] Snort Community 下载失败或为空，跳过"
fi

# 统计并设置权限
TOTAL_COUNT=$(grep -c '^alert\|^drop\|^reject' "$COMBINED_RULES" 2>/dev/null || echo 0)
chmod 644 "$COMBINED_RULES"
echo "[+] combined.rules 已生成（${TOTAL_COUNT} 条规则），路径: $COMBINED_RULES"

# 规则文件在宿主机，suricata 容器通过 /var/lib/suricata/rules 挂载读取
# 先用 suricata -T 校验规则语法，自动剔除 Snort 社区规则中不兼容的规则，通过后再重启加载
echo "[*] 5.4 校验规则语法并自动修复不兼容规则 (suricata -T)..."
MAX_FIX_RETRY=5
for fix_i in $(seq 1 $MAX_FIX_RETRY); do
    TEST_OUTPUT=$(docker exec suricata suricata -T -c /etc/suricata/suricata.yaml 2>&1) || true
    TEST_RC=$?
    echo "$TEST_OUTPUT" | grep -E "rule|Rule|error|Error|WARN|FAIL|loaded|FAILED" | tail -10
    if [ "$TEST_RC" -eq 0 ]; then
        echo "[+] 规则语法校验通过，重启 suricata 加载新规则..."
        docker restart suricata
        break
    fi
    # 从错误输出中提取行号（如 "at line 5139"），删除对应规则行
    ERR_LINE=$(echo "$TEST_OUTPUT" | grep -oP 'at line \K\d+' | head -1)
    if [ -n "$ERR_LINE" ]; then
        echo "  [!] 第 ${fix_i}/${MAX_FIX_RETRY} 次：删除 combined.rules 第 ${ERR_LINE} 行不兼容规则"
        sed -i "${ERR_LINE}d" "$COMBINED_RULES"
    else
        echo "[!] 规则语法校验失败（${fix_i}/${MAX_FIX_RETRY}），且无法定位错误行号，跳过重启" >&2
        break
    fi
done

# 6. 阅后即焚：擦除 Shell 进程中的环境变量
unset PUID PGID

# 打印提示信息（密码从 .env 读取，方便部署者访问；<IP> 为固定占位符，无需动态获取）
ENV_FILE="$BASE_DIR/.env"
ELASTIC_PASSWORD=$(grep '^ELASTIC_PASSWORD=' "$ENV_FILE" 2>/dev/null | cut -d'=' -f2-)
if [ -z "$ELASTIC_PASSWORD" ]; then
    echo "[-] 错误：ELASTIC_PASSWORD 为空，请检查 $ENV_FILE"
    exit 1
fi

echo "[+] =============================================="
echo "[+] SOC 堆栈已安全启动！"
echo "[+] 访问地址：https://<IP>:8080"
echo "[+] 默认用户名/密码：admin/${ELASTIC_PASSWORD}"
echo "[+] =============================================="