#!/bin/bash
set -e
# If the script was invoked with sh, re-exec under bash so bash-specific
# features like PIPESTATUS work correctly.
if [ -z "${BASH_VERSION:-}" ]; then
    if command -v bash >/dev/null 2>&1; then
        exec bash "$0" "$@"
    else
        echo "[-] 错误：此脚本需要 bash，请使用 bash 运行：sudo bash $0 <interface>" >&2
        exit 1
    fi
fi
# Base directory of the script (absolute) to reliably locate .env when
# the script is executed via sudo or different working directories.
BASE_DIR=$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd)

########################################
# 依赖检查（全新机器必需）
########################################
check_dependency() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "[-] 错误：缺少依赖 '$1'，请先安装：apt install -y $2"
        exit 1
    fi
}

check_dependency docker "docker.io docker-compose-plugin"
check_dependency curl "curl"
check_dependency jq "jq"
check_dependency unzip "unzip"
check_dependency openssl "openssl"

# 检查 docker compose 子命令（v2 插件）
if ! docker compose version >/dev/null 2>&1; then
    echo "[-] 错误：需要 Docker Compose V2（docker compose 子命令），请安装 docker-compose-plugin"
    exit 1
fi

echo "[+] 依赖检查通过"

usage() {
    cat <<EOF
Usage: $0 <interface>

You must specify the network interface to use with Suricata and Zeek.
Example: sudo sh ./deploy.sh ens192
EOF
}

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    usage
    exit 0
fi

if [ -z "$1" ]; then
    echo "[-] 错误：必须指定网卡接口。"
    usage
    exit 1
fi

INTERFACE=$1
export INTERFACE

if command -v ip >/dev/null 2>&1; then
    if ! ip link show "$INTERFACE" >/dev/null 2>&1; then
        echo "[-] 错误：网卡接口 '$INTERFACE' 不存在。"
        exit 1
    fi
    echo "[*] 0. 配置网络接口 $INTERFACE：开启混杂模式并禁用 offload"
    ip link set "$INTERFACE" promisc on
fi

if command -v ethtool >/dev/null 2>&1; then
    ethtool -K "$INTERFACE" gro off || true
    ethtool -K "$INTERFACE" lro off || true
    ethtool -K "$INTERFACE" tso off || true
    ethtool -K "$INTERFACE" gso off || true
    # 禁用 RX/TX checksum offload，避免网卡硬件计算 checksum 导致
    # Zeek/Suricata 在混杂模式下捕获到错误 checksum（如 tcp checksum incorrect），
    # 进而影响 payload 解析和 http_request_body 提取
    ethtool -K "$INTERFACE" rx off || true
    ethtool -K "$INTERFACE" tx off || true
fi

# 持久化网卡配置：创建 systemd 服务，重启后自动恢复混杂模式和 offload 禁用
NET_SERVICE="/etc/systemd/system/sensemind-network.service"
cat > "$NET_SERVICE" << EOF
[Unit]
Description=SenseMind network interface configuration
After=network.target network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/bash -c 'ip link set $INTERFACE promisc on; ethtool -K $INTERFACE gro off lro off tso off gso off rx off tx off 2>/dev/null || true'

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable sensemind-network.service 2>/dev/null
echo "[+] 网卡配置已持久化（sensemind-network.service，开机自动执行）"

export PUID=$(id -u)
export PGID=$(id -g)

echo "[*] 构建/拉取 Docker 镜像..."

# 证书生成依赖 elasticsearch 镜像（certutil），需提前拉取
ES_IMAGE="docker.elastic.co/elasticsearch/elasticsearch:8.19.16"
if ! docker image inspect "$ES_IMAGE" >/dev/null 2>&1; then
    echo "[*] 拉取 Elasticsearch 镜像（证书生成依赖）..."
    docker pull "$ES_IMAGE" || {
        echo "[-] 拉取 Elasticsearch 镜像失败，请检查网络/代理。"
        exit 1
    }
fi

########################################
# 0.1 预生成 Elasticsearch SSL 证书
#     在启动任何容器之前生成，打破"先有ES还是先有证书"的循环依赖
########################################
CERTS_DIR="$BASE_DIR/certs"
if [ ! -f "$CERTS_DIR/elastic-certificates.p12" ] || [ ! -f "$CERTS_DIR/ca.crt" ]; then
    echo "[*] 生成 Elasticsearch SSL 证书（首次部署，有效期 10 年）..."
    mkdir -p "$CERTS_DIR"
    # ES 容器内 certutil 以 uid 1000(elasticsearch) 运行，而本目录由 sudo(root)
    # 创建且默认 755，uid 1000 无法写入会抛 AccessDeniedException。临时放开写权限。
    chmod 777 "$CERTS_DIR"

    # 1. 生成 CA（PEM 格式，便于 Logstash 使用）
    #    -s/--silent 抑制 certutil 默认输出的大段帮助说明
    #    --dn 自定义 CA 公用名（默认为 Elastic Certificate Tool Autogenerated CA）
    docker run --rm \
        -v "$CERTS_DIR:/certs" \
        --entrypoint /usr/share/elasticsearch/bin/elasticsearch-certutil \
        docker.elastic.co/elasticsearch/elasticsearch:8.19.16 \
        ca --pem --out /certs/ca.zip --days 3650 -s \
        --ca-dn "CN=SenseMind CA,O=SenseMind"

    # 2. 解压 CA → certs/ca/ca.crt, certs/ca/ca.key
    if ! command -v unzip >/dev/null 2>&1; then
        echo "[-] 错误：需要 unzip 工具来解压证书，请先安装：apt install -y unzip"
        exit 1
    fi
    (cd "$CERTS_DIR" && unzip -oq ca.zip)

    # 3. 生成节点证书（PKCS12，用于 ES transport + HTTP SSL）
    docker run --rm \
        -v "$CERTS_DIR:/certs" \
        --entrypoint /usr/share/elasticsearch/bin/elasticsearch-certutil \
        docker.elastic.co/elasticsearch/elasticsearch:8.19.16 \
        cert --out /certs/elastic-certificates.p12 --pass "" \
        --ca-cert /certs/ca/ca.crt --ca-key /certs/ca/ca.key \
        --dns elasticsearch,localhost --ip 127.0.0.1 --days 3650 -s

    # 4. 将 ca.crt 复制到 certs 根目录，方便挂载
    cp "$CERTS_DIR/ca/ca.crt" "$CERTS_DIR/ca.crt"

    # 5. 清理临时文件
    rm -f "$CERTS_DIR/ca.zip"

    # 6. 设置权限
    chmod 644 "$CERTS_DIR/ca.crt" "$CERTS_DIR/elastic-certificates.p12"

    echo "[+] SSL 证书已生成: $CERTS_DIR/"
    echo "    - ca.crt                    (CA 证书，Logstash 用)"
    echo "    - elastic-certificates.p12   (节点证书，ES 用)"
else
    echo "[+] SSL 证书已存在，跳过生成"
fi

########################################
# 0.1.1 为 web 前端签发 HTTPS 证书
#       复用 ES 的 CA（ca.crt + ca.key），SAN 包含本机 IP，供 nginx 使用
########################################
if [ ! -f "$CERTS_DIR/web.crt" ] || [ ! -f "$CERTS_DIR/web.key" ]; then
    echo "[*] 为 web 前端签发 HTTPS 证书（复用 ES CA）..."
    # 收集本机非 loopback IPv4 地址，加入 SAN（浏览器用 IP 访问时需匹配）
    WEB_SAN="DNS:localhost,IP:127.0.0.1"
    for ip in $(hostname -I 2>/dev/null | tr ' ' '\n' | grep -E '^[0-9]+\.' | grep -v '^127\.' | sort -u); do
        WEB_SAN="${WEB_SAN},IP:${ip}"
    done
    # 生成私钥
    openssl genrsa -out "$CERTS_DIR/web.key" 2048 2>/dev/null
    # 生成 CSR
    openssl req -new -key "$CERTS_DIR/web.key" -out "$CERTS_DIR/web.csr" \
        -subj "/CN=sensemind-web" 2>/dev/null
    # SAN 扩展配置
    printf "subjectAltName=%s\nextendedKeyUsage=serverAuth\n" "$WEB_SAN" > "$CERTS_DIR/web.ext"
    # 用 ES 的 CA 签发（有效期 10 年）
    openssl x509 -req -in "$CERTS_DIR/web.csr" \
        -CA "$CERTS_DIR/ca/ca.crt" -CAkey "$CERTS_DIR/ca/ca.key" \
        -CAcreateserial -out "$CERTS_DIR/web.crt" -days 3650 -sha256 \
        -extfile "$CERTS_DIR/web.ext" 2>/dev/null
    # 清理临时文件（-CAcreateserial 在 CA 同目录生成 ca.srl）
    rm -f "$CERTS_DIR/web.csr" "$CERTS_DIR/web.ext" "$CERTS_DIR/ca/ca.srl"
    chmod 644 "$CERTS_DIR/web.crt"
    chmod 600 "$CERTS_DIR/web.key"
    echo "[+] web HTTPS 证书已签发: web.crt / web.key"
    echo "    SAN: $WEB_SAN"
    echo "    注意：自签 CA，浏览器首次访问会提示不安全，导入 certs/ca.crt 到系统/浏览器信任库即可消除"
else
    echo "[+] web HTTPS 证书已存在，跳过签发"
fi

########################################
# 0.2 清理残留容器
#     - 非全新部署时，上次失败可能残留容器，按服务名强制移除避免重名冲突
########################################
echo "[*] 清理可能残留的旧容器..."
docker compose down --remove-orphans 2>/dev/null >/dev/null || true
docker compose config --services 2>/dev/null | xargs -r docker rm -f >/dev/null 2>&1 || true

echo "[*] =============================================="

echo "[*] 1. 初始化环境变量文件..."
ENV_FILE="$BASE_DIR/.env"
if [ -f "$ENV_FILE" ]; then
    cp -f "$ENV_FILE" "${ENV_FILE}.bak" >/dev/null 2>&1 || true
fi
touch "$ENV_FILE"
chmod 600 "$ENV_FILE"
echo "[+] 环境变量文件已就绪: $ENV_FILE（权限 600）"

# Ensure LOGSTASH_API_KEY exists to avoid docker-compose warnings when referenced
grep -q '^LOGSTASH_API_KEY=' "$ENV_FILE" 2>/dev/null || echo 'LOGSTASH_API_KEY=' >> "$ENV_FILE"

# 持久化监听网卡到 .env，避免后续 docker compose 重启（如 reboot、手动 up）
# 回退到默认 ens192 导致 Suricata/Zeek 因网卡不存在而崩溃
grep -q '^INTERFACE=' "$ENV_FILE" 2>/dev/null && \
  sed -i "s/^INTERFACE=.*/INTERFACE=$INTERFACE/" "$ENV_FILE" || \
  echo "INTERFACE=$INTERFACE" >> "$ENV_FILE"

# 确保 filebeat.yml 的权限和所有者符合 Filebeat 要求
if [ -f "$BASE_DIR/filebeat/filebeat.yml" ]; then
    echo "[*] 修改 filebeat/filebeat.yml 权限，确保容器内 filebeat 可读取"
    chown root:root "$BASE_DIR/filebeat/filebeat.yml"
    chmod 600 "$BASE_DIR/filebeat/filebeat.yml"
fi

# 预创建宿主机 Suricata/Zeek 目录，以便日志、配置和规则持久化
mkdir -p /data/suricata/logs /data/suricata/lib /data/suricata/lib/rules /data/suricata/etc /data/zeek/logs
chmod 755 /data /data/suricata /data/zeek /data/suricata/logs /data/suricata/lib /data/suricata/lib/rules /data/suricata/etc /data/zeek/logs

# 创建 Zeek 日志过滤脚本（仅保留 conn 做全流量记录，dns/http/ssl 不再输出）。
# 注意：必须创建为“文件”，docker 才会把宿主机路径作为文件挂载到 /opt/zeek-log-filter.zeek；
# 若此处漏建，docker 会自动用同名“空目录”挂载，导致 zeek 把目录当包加载而崩溃循环。
if [ ! -f /data/zeek/zeek-log-filter.zeek ]; then
    cat > /data/zeek/zeek-log-filter.zeek <<'ZEEK_FILTER_EOF'
# SenseMind Zeek 日志过滤脚本
# 仅保留 conn 日志流做全流量记录；dns / http / ssl 不再输出（其余协议本就禁用）。
# 本脚本随 zeek 启动命令加载（未经过 site/local.zeek）。
#
# 实现：运行时遍历 Log::active_streams（priority=-10，在各协议脚本 zeek_init
# 创建日志流之后执行）反向保留，其余一律 disable_stream。
# 相比旧的逐个 @ifdef 点名禁用，此法可彻底规避两类问题：
#   1) 漏项：新协议（kerberos/rdp/sip/pe/postgresql/ldap_search/mqtt_subscribe 等）
#      无需逐个补充，凡不在保留集内一律禁用；
#   2) 编译期命名空间不可见：@ifdef 会对 analyzer/mysql/quic 等判假跳过导致禁用失效，
#      而遍历运行时已存在的 active_streams 不受此限制。
# 注：conn 属 base 协议，命名空间始终可见，直接引用其 Log::ID 安全。

module SenseMindFilter;

# 保留的日志流：仅 conn（全流量记录）
const keep_streams: set[Log::ID] = {
    Conn::LOG,
};

event zeek_init() &priority=-10
    {
    # 先收集待禁用的流，再统一禁用；避免在遍历 active_streams 的同时
    # disable_stream 修改该表引发迭代器失效（iterator invalidation）。
    local to_disable: set[Log::ID] = set();
    for ( sid in Log::active_streams )
        {
        if ( sid !in keep_streams )
            add to_disable[sid];
        }
    for ( sid in to_disable )
        Log::disable_stream(sid);
    }

# 减少 conn.log 体积：写盘前剔除与 SOC 分析冗余或纯噪音的连接。
# 不丢安全价值——443/80/业务应用端口全部保留，供威胁狩猎与横向移动检测。
# 排除项（基于实际流量分析）：
#   - DNS(53)：DNS 连接噪音，conn 中冗余（约占 14%）
#   - LLMNR(5355)/mDNS(5353)/SSDP(1900)/NetBIOS(137/138/139)：本地发现广播噪音
#   - NTP(123)/DHCP(67/68)：无安全分析价值
#   - 组播/广播目的地址（224.0.0.0/4，如 LLMNR 224.0.0.252）
const conn_noise_ports: set[port] = {
    53/udp, 53/tcp,
    5355/udp, 5353/udp, 1900/udp,
    137/udp, 138/udp, 139/tcp,
    123/udp, 67/udp, 68/udp,
};

# Zeek 8.2 移除 filter$invalidate 字段，改用 break 否决该记录写入。
hook Conn::log_policy(rec: Conn::Info, id: Log::ID, filter: Log::Filter)
    {
    if ( ! rec?$id ) return;
    if ( rec$id$resp_p in conn_noise_ports )
        break;
    if ( rec$id$resp_h in 224.0.0.0/4 )
        break;
    }

ZEEK_FILTER_EOF
    chmod 644 /data/zeek/zeek-log-filter.zeek
fi

chown -R "$PUID:$PGID" /data/suricata/logs /data/suricata/lib /data/suricata/lib/rules /data/suricata/etc

echo "[*] 2. 准备 elastic 密码并启动 Elasticsearch..."
# ES 8.x 首次启动（安全索引不存在）时，若设置了 ELASTIC_PASSWORD 环境变量，
# 会以此引导 elastic 用户密码；后续启动忽略该变量。
# 这避免了在 SSL 启用后 elasticsearch-reset-password CLI（需信任自签 CA）的麻烦。
EXISTING_PWD=$(grep '^ELASTIC_PASSWORD=' "$ENV_FILE" 2>/dev/null | cut -d= -f2-)
if [ -n "$EXISTING_PWD" ]; then
    ELASTIC_PASSWORD="$EXISTING_PWD"
    echo "[+] 使用已有 elastic 密码"
else
    ELASTIC_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)
    grep -v '^ELASTIC_PASSWORD=' "$ENV_FILE" 2>/dev/null > "${ENV_FILE}.tmp" || true
    echo "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}" >> "${ENV_FILE}.tmp"
    mv "${ENV_FILE}.tmp" "$ENV_FILE"
    chmod 600 "$ENV_FILE"
    echo "[+] elastic 密码已生成并写入 .env（ES 首次启动将以引导）"
fi
export ELASTIC_PASSWORD

docker compose up -d elasticsearch

echo "[*] 3. 等待 Elasticsearch 完全就绪..."
while true; do
    # 获取容器当前运行状态和健康状态
    STATUS=$(docker inspect --format='{{.State.Status}}' elasticsearch 2>/dev/null || echo "not_found")
    HEALTH=$(docker inspect --format='{{.State.Health.Status}}' elasticsearch 2>/dev/null || echo "none")

    if [ "$HEALTH" = "healthy" ]; then
        printf "\n[+] Elasticsearch 已进入 Healthy 状态!\n"
        break
    fi

    if [ "$STATUS" != "running" ]; then
        printf "\n[-] 错误：Elasticsearch 容器未能成功运行，当前状态：%s\n" "$STATUS"
        exit 1
    fi

    printf "."
    sleep 2
done

echo "[*] 3.1 验证 elastic 密码..."
# 密码已在启动 ES 前写入 .env，ES 首次启动时以 ELASTIC_PASSWORD 引导。
# 此处仅验证密码是否生效（curl -sk 跳过证书校验，从宿主机经端口映射访问）。
PWD_OK=false
for i in $(seq 1 20); do
    PWD_CHECK=$(curl -sk -o /dev/null -w "%{http_code}" --max-time 5 \
        -u "elastic:${ELASTIC_PASSWORD}" "https://localhost:9200/" 2>/dev/null) || true
    if [ "$PWD_CHECK" = "200" ]; then
        PWD_OK=true
        echo "[+] elastic 密码验证通过 (尝试 $i/20)"
        break
    fi
    printf "."
    sleep 3
done

if [ "$PWD_OK" != "true" ]; then
    printf "\n[-] 错误：elastic 密码验证失败（最后 HTTP 状态码: %s）\n" "${PWD_CHECK:-000}"
    echo "[-] 若复用旧数据卷(esdata)，ES 会忽略 ELASTIC_PASSWORD 而沿用旧密码。"
    echo "[-] 请清理后重试：sudo bash remove.sh && sudo bash deploy.sh $INTERFACE"
    exit 1
fi

echo "[*] 3.2 正在等待 Elasticsearch 安全模块完全就绪..."

# 使用脚本开头定义的 BASE_DIR 绝对路径加载环境变量
if [ ! -f "$BASE_DIR/.env" ]; then
    echo "[-] 致命错误：找不到 $BASE_DIR/.env"
    exit 1
fi
. "$BASE_DIR/.env"

# 显式检查密码变量
if [ -z "${ELASTIC_PASSWORD}" ]; then
    echo "[-] 致命错误：ELASTIC_PASSWORD 为空！.env 内容如下："
    grep "PASSWORD\|TOKEN\|KEY" "$BASE_DIR/.env" || true
    exit 1
fi

AUTH_READY=false
for i in $(seq 1 20); do
    # 分离 curl 执行与状态码提取，避免管道或子shell导致的 set -e 陷阱
    CURL_OUTPUT=$(curl -sk -o /dev/null -w "%{http_code}" --max-time 5 \
        -u "elastic:${ELASTIC_PASSWORD}" \
        "https://localhost:9200/_security/_authenticate" 2>/dev/null) || true
    
    AUTH_CODE="${CURL_OUTPUT:-000}"
    
    if [ "$AUTH_CODE" = "200" ]; then
        AUTH_READY=true
        echo "[+] Elasticsearch 安全模块已就绪 (尝试 $i/20)"
        break
    fi
    
    printf "."
    sleep 3
done

if [ "$AUTH_READY" != "true" ]; then
    echo ""
    echo "[-] 错误：Elasticsearch 安全模块在 60 秒内未就绪"
    echo "[-] 最后认证响应码: ${AUTH_CODE}"
    docker logs elasticsearch --tail 50 2>&1 | grep -iE "security|exception|error|authentication" || true
    exit 1
fi

echo "[*] 3.4 正在生成 logstash API Key..."

# 确保从 .env 读取到最新的密码
. "$ENV_FILE"

if [ -z "$ELASTIC_PASSWORD" ]; then
    echo "[-] 错误：.env 中未找到 ELASTIC_PASSWORD"
    exit 1
fi

# 增加重试机制，等待安全索引同步完成
MAX_RETRIES=10
RETRY_COUNT=0
LOGSTASH_API_KEY=""

while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
    RESPONSE=$(curl -sk -u "elastic:${ELASTIC_PASSWORD}" \
        -X POST "https://localhost:9200/_security/api_key" \
        -H "Content-Type: application/json" \
        -d '{
          "name": "logstash-soc",
          "role_descriptors": {
            "logstash_writer": {
              "cluster": ["monitor", "read_ilm", "manage_index_templates", "manage_ingest_pipelines"],
              "index": [
                {
                  "names": ["*"],
                  "privileges": ["write", "create", "create_index", "auto_configure", "view_index_metadata"]
                }
              ]
            }
          }
        }')

    # 尝试解析 API Key
    LOGSTASH_API_KEY=$(echo "$RESPONSE" | jq -r 'if .id and .api_key then (.id + ":" + .api_key) else empty end' 2>/dev/null)

    if [ -n "$LOGSTASH_API_KEY" ] && [ "$LOGSTASH_API_KEY" != "null:null" ]; then
        break
    fi

    RETRY_COUNT=$((RETRY_COUNT + 1))
    echo "[!] API Key 生成失败 (尝试 $RETRY_COUNT/$MAX_RETRIES)，ES 响应: $RESPONSE"
    echo "[*] 等待 3 秒后重试..."
    sleep 3
done

if [ -z "$LOGSTASH_API_KEY" ] || [ "$LOGSTASH_API_KEY" = "null:null" ]; then
    echo "[-] 错误：API Key 生成失败，已达最大重试次数"
    echo "[-] 最后一次 ES 响应: $RESPONSE"
    exit 1
fi

echo "[+] logstash API Key 已生成并验证通过"

export LOGSTASH_API_KEY

# 写入 .env（追加）
grep -v '^LOGSTASH_API_KEY=' "$ENV_FILE" 2>/dev/null > "${ENV_FILE}.tmp" || true
echo "LOGSTASH_API_KEY=${LOGSTASH_API_KEY}" >> "${ENV_FILE}.tmp"
mv "${ENV_FILE}.tmp" "$ENV_FILE"
chmod 600 "$ENV_FILE"

echo "[+] logstash API Key 已生成并写入 .env"

echo "[*] 3.5 正在生成 ES Reader API Key (sensemind-reader)..."

# 先清理可能存在的同名旧 API Key，避免累积（幂等）
OLD_ES_READER_IDS=$(curl -sk -u "elastic:${ELASTIC_PASSWORD}" \
    "https://localhost:9200/_security/api_key?name=sensemind-reader" 2>/dev/null \
    | jq -r '.api_keys[]? | select(.invalidated==false) | .id' 2>/dev/null) || true
for kid in $OLD_ES_READER_IDS; do
    curl -sk -u "elastic:${ELASTIC_PASSWORD}" -X DELETE \
        "https://localhost:9200/_security/api_key" \
        -H "Content-Type: application/json" \
        -d "{\"ids\":[\"$kid\"]}" >/dev/null 2>&1 || true
done

# 创建专用只读 API Key：仅授予 soc-*/soc-ai-* 索引读权限
# ai-analyzer 使用此 Key 替代 elastic 密码访问 ES（最小权限原则）
ES_READER_RESP=$(curl -sk -u "elastic:${ELASTIC_PASSWORD}" \
    -X POST "https://localhost:9200/_security/api_key" \
    -H "Content-Type: application/json" \
    -d '{
      "name": "sensemind-reader",
      "role_descriptors": {
        "sensemind_reader": {
          "cluster": ["monitor"],
          "index": [
            {
              "names": ["soc-*", "soc-ai-*"],
              "privileges": ["read", "view_index_metadata"]
            }
          ]
        }
      }
    }')

# 取 encoded 字段（已为 id:api_key 的 Base64 编码，可直接用于 Authorization: ApiKey 头）
ES_READER_API_KEY=$(echo "$ES_READER_RESP" | jq -r '.encoded // empty' 2>/dev/null)

if [ -z "$ES_READER_API_KEY" ]; then
    echo "[-] 错误：sensemind-reader API Key 生成失败！ES 响应: $ES_READER_RESP"
    exit 1
fi

echo "[+] ES Reader API Key 已生成"
export ES_READER_API_KEY

# 写入 .env（更新或追加）
grep -v '^ES_READER_API_KEY=' "$ENV_FILE" 2>/dev/null > "${ENV_FILE}.tmp" || true
echo "ES_READER_API_KEY=${ES_READER_API_KEY}" >> "${ENV_FILE}.tmp"
mv "${ENV_FILE}.tmp" "$ENV_FILE"
chmod 600 "$ENV_FILE"

echo "[+] ES Reader API Key 已写入 .env"

echo "[*] 3.5 正在生成 JWT 与加密密钥..."
# SECRET_KEY: JWT 签名密钥（32 字节 hex），用于认证 token 签发与校验
# ENCRYPT_KEY: TOTP secret 加密密钥，用于 Fernet/PBKDF2 派生
# 仅首次生成，后续部署复用 .env 中已有值（密钥不可变更，否则已有 JWT 失效、TOTP 无法解密）
EXISTING_SECRET_KEY=$(grep '^SECRET_KEY=' "$ENV_FILE" 2>/dev/null | cut -d= -f2-)
EXISTING_ENCRYPT_KEY=$(grep '^ENCRYPT_KEY=' "$ENV_FILE" 2>/dev/null | cut -d= -f2-)

if [ -z "$EXISTING_SECRET_KEY" ]; then
    SECRET_KEY=$(openssl rand -hex 32)
    echo "SECRET_KEY=${SECRET_KEY}" >> "$ENV_FILE"
    echo "[+] SECRET_KEY 已生成并写入 .env"
else
    echo "[+] 使用已有 SECRET_KEY"
fi

if [ -z "$EXISTING_ENCRYPT_KEY" ]; then
    # core/security.py 用 PBKDF2 从 ENCRYPT_KEY 派生 Fernet 密钥，对格式不敏感，任意字符串即可
    ENCRYPT_KEY=$(openssl rand -base64 32)
    echo "ENCRYPT_KEY=${ENCRYPT_KEY}" >> "$ENV_FILE"
    echo "[+] ENCRYPT_KEY 已生成并写入 .env"
else
    echo "[+] 使用已有 ENCRYPT_KEY"
fi
chmod 600 "$ENV_FILE"

# 4. 一键拉起整套 SOC 堆栈（Suricata, Zeek）
#    先构建本地镜像（web、ai-analyzer），避免 up 时尝试从远程拉取本地镜像
echo "[*] 4. 正在拉起探针与展示层..."

# 预拉取构建基础镜像（BuildKit 不走 Docker daemon 代理，需先 docker pull 缓存到本地）
BASE_IMAGES="python:3.12-slim node:20-alpine nginx:1.27-alpine"
for IMG in $BASE_IMAGES; do
    if ! docker image inspect "$IMG" >/dev/null 2>&1; then
        echo "[+] 拉取基础镜像 $IMG ..."
        docker pull "$IMG" || echo "[!] 拉取 $IMG 失败，若已有缓存可继续。"
    fi
done

docker compose build
docker compose up -d

echo "[*] 4.1 强制重启 logstash 以加载最新 API Key..."
docker compose up -d --force-recreate logstash

echo "[*] 4.2 强制重启 ai-analyzer 以加载 ES Reader API Key..."
docker compose up -d --force-recreate ai-analyzer

# 修改 Suricata 配置：community-id、payload、http-body-inline、local.rules
# jasonish/suricata 容器启动时会自动复制默认配置到挂载目录
SURICATA_YAML="/data/suricata/etc/suricata.yaml"
if [ -f "$SURICATA_YAML" ]; then
    # 创建 local.rules 文件（AI 自动生成的本地规则）
    # 规则目录与 suricata.yaml 的 default-rule-path 一致: /var/lib/suricata/rules
    touch /data/suricata/lib/rules/local.rules
    chmod 666 /data/suricata/lib/rules/local.rules

    # 开启 alert 事件的 HTTP body 记录，供 AI 判断攻击是否成功
    # http-body: Base64 编码的完整响应体（保留中文），由 ai-analyzer 解码
    # http-body-printable: 可打印格式（中文被替换为.），作为回退
    # 两者都是 - alert: 部分的选项，需要 metadata 启用才会生效
    # 同时清理 - http: 部分下旧版误加的非注释 http-body-printable 行
    sed -i -E \
      -e 's/community-id: false/community-id: true/' \
      -e '/- alert:/,/- frame:/ { s/# *(payload-buffer-size:)/\1/; s/# *(payload-printable:)/\1/; s/# *(http-body-printable:)/\1/; s/# *(http-body: yes)/\1/ }' \
      -e '/^[[:space:]]*- http:/,/^[[:space:]]*- [a-z]/ { /^[[:space:]]*http-body-printable:/d }' \
      -e 's/http-body-inline: auto/http-body-inline: yes/' \
      "$SURICATA_YAML"

    # 添加 local.rules 到 rule-files（相对于 default-rule-path，只需写文件名）
    # suricata 8.x unix-command 默认 enabled: auto，无需额外配置
    if ! grep -q 'local.rules' "$SURICATA_YAML"; then
        sed -i '/- suricata\.rules/a\  - local.rules' "$SURICATA_YAML"
    fi

    # 源头禁用 eve-log 的 stats/flow/mdns/files/snmp/dcerpc（SOC 不入库，纯协议元数据噪音）
    sed -i -E \
      -e '/^[[:space:]]{8}- stats:/,/^[[:space:]]*# bi-directional flows/ s/^/# /' \
      -e 's/^([[:space:]]{8})- flow$/# \1- flow/' \
      -e 's/^([[:space:]]{8})- mdns:$/# \1- mdns:/' \
      -e 's/^([[:space:]]{8})- files:$/# \1- files:/' \
      -e 's/^([[:space:]]{12})force-magic: no.*$/# \1force-magic: no/' \
      -e 's/^([[:space:]]{8})- snmp$/# \1- snmp/' \
      -e 's/^([[:space:]]{8})- dcerpc$/# \1- dcerpc/' \
      "$SURICATA_YAML"

    docker restart suricata
    echo "[+] Suricata 配置已更新并重启（含 local.rules 加载，suricatasc 热加载就绪）"
else
    echo "[-] 警告：Suricata 配置文件 $SURICATA_YAML 未找到，跳过配置修改。"
fi

echo "[*] 4.3 部署 Suricata 规则抑制配置 disable.conf（按组禁用误报，重部署不复活）..."
DISABLE_CONF="/data/suricata/lib/rules/disable.conf"
SRC_DISABLE_CONF="$(dirname "$0")/suricata/disable.conf"
if [ -f "$SRC_DISABLE_CONF" ]; then
    cp -f "$SRC_DISABLE_CONF" "$DISABLE_CONF"
    chmod 644 "$DISABLE_CONF"
    echo "[+] disable.conf 已从仓库拷贝: $SRC_DISABLE_CONF -> $DISABLE_CONF"
else
    echo "[!] 警告：仓库 suricata/disable.conf 不存在，跳过（规则抑制将不生效）"
fi

echo "[*] 5. 更新 Suricata 规则 suricata-update (-f)，将显示实时输出："

docker exec --user suricata suricata suricata-update update-sources || true

echo "[*] 正在启用免费 Suricata 规则源（排除低价值噪音源）..."
# 永久排除的商业/低价值源（其余免费源保留启用）：oisf/trafficid、pawpatrules、julioliraup/antiphishing、
# ipfire/dbl、aleksibovellan/nmap、tgreen/hunting（github 常超时+误报高）、the-hunters-ledger/open（THL 误报偏高）。
ENABLED_MSG=$(docker exec suricata sh -c "suricata-update list-sources 2>/dev/null | sed -E 's/\x1b\[[0-9;]*m//g' | tr -d '\r' | awk '/^Name:/{name=\$2} /^[[:space:]]+License:/{if(\$2!=\"Commercial\" && name!=\"oisf/trafficid\" && name!=\"pawpatrules\" && name!=\"julioliraup/antiphishing\" && name!=\"ipfire/dbl\" && name!=\"aleksibovellan/nmap\" && name!=\"tgreen/hunting\" && name!=\"the-hunters-ledger/open\") print name}' | tee /tmp/free_sources.txt | xargs -r -n1 suricata-update enable-source >/dev/null 2>&1; count=\$(wc -l < /tmp/free_sources.txt); rm -f /tmp/free_sources.txt; echo \"已启用 \${count} 个免费规则源（已永久排除 tgreen/hunting、the-hunters-ledger/open）\"")
echo "$ENABLED_MSG"

TMP_LOG=$(mktemp)
set +e
# 首次部署（零缓存）时，部分源可能无缓存且拉取超时 -> suricata-update 致命中断、不写规则、disable.conf 不生效。
# 重试：每次成功的源会建立缓存，后续该源即用缓存继续，逐步逼近完整规则集并让 disable.conf 生效。
MAX_RETRY=8
RET=1
for i in $(seq 1 $MAX_RETRY); do
    docker exec --user suricata suricata suricata-update -f --disable-conf /var/lib/suricata/rules/disable.conf 2>&1 | tee "$TMP_LOG"
    RET=${PIPESTATUS[0]}
    if [ "$RET" -eq 0 ]; then
        break
    fi
    echo "[-] 第 $i/$MAX_RETRY 次规则更新失败（部分源拉取超时），10s 后重试以累积缓存..." >&2
    sleep 10
done
set -e

if [ "$RET" -eq 0 ]; then
    echo "[+] Suricata 规则已下载并重新加载。"
    rm -f "$TMP_LOG"
else
    echo "[-] suricata-update 连续 $MAX_RETRY 次失败（退出码 $RET）" >&2
    echo "[-] suricata-update 错误摘要：" >&2
    grep -v "<Info>" "$TMP_LOG" | tail -n 30 >&2
    rm -f "$TMP_LOG"

    echo "[-] Suricata 引擎日志（最后 200 行）：" >&2
    docker exec suricata sh -c 'tail -n 200 /var/log/suricata/suricata.log 2>/dev/null || true' >&2

    # 兜底：用已建缓存离线生成规则并应用 disable.conf。
    # 注：若仍有源“完全无缓存”（持续超时从未成功），--offline 会因该源缺失而致命，
    # 此时 disable.conf 仅对成功加载的源生效；该源规则缺失，待网络恢复后手动补拉即可。
    echo "[-] 尝试 --offline 兜底（用已有缓存生成规则并应用 disable.conf）..."
    docker exec --user suricata suricata suricata-update -f --offline --disable-conf /var/lib/suricata/rules/disable.conf 2>&1 | tail -8
    echo -e "\033[33m[-] 部分规则源可能仍因持续超时未加载。disable.conf 已对成功加载的源生效。网络恢复后可手动补拉：\033[36mdocker exec --user suricata suricata suricata-update -f --disable-conf /var/lib/suricata/rules/disable.conf\033[33m\033[0m" >&2
fi

# 规则抑制已统一由 suricata-update --disable-conf 处理（见上方生成的 disable.conf），
# 不再用 sed 注释 suricata.rules（suricata-update -f 会重写规则，sed 会被覆盖）。
docker restart suricata

# 6. 阅后即焚：擦除 Shell 进程中的环境变量
unset PUID PGID
echo "[+] =============================================="
echo "[+] SOC 堆栈已安全启动。当前 Shell 敏感凭据已全数清空！"

# 7. 打印提示信息
ENV_FILE=".env"
if [ -f "$ENV_FILE" ]; then
    ELASTIC_PASSWORD=$(grep '^ELASTIC_PASSWORD=' "$ENV_FILE" | cut -d'=' -f2-)
else
    echo "❌ 未找到 $ENV_FILE 文件"
    exit 1
fi

if [ -z "$ELASTIC_PASSWORD" ]; then
    echo "❌ ELASTIC_PASSWORD 为空，请检查 $ENV_FILE"
    exit 1
fi

# 打印提示信息（<IP> 为固定占位符，无需动态获取）
echo "[+] =============================================="
echo " 默认用户名/密码：admin/${ELASTIC_PASSWORD}"
echo " 访问地址：https://<IP>:8080"
echo "[+] =============================================="